version: '3.8'

services:
  backend:
    build: ./dc1  # Path to Django Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env  # Store secrets here
    ports:
      - "8000:8000"
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass  # Change this!
      MYSQL_DATABASE: chatdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass  # Change this!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  nginx:
    build: ./nginx  # Path to Nginx Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
